name: 04 - Using Actions

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        # 1. install dependencies of react app
        # 2. Execute the test cases
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Printing Folders
              run: ls
