name: 03 - Workflow Runners

on: push

jobs:
  ubuntu-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show OS version
        run: |
          echo "This job is running on Ubuntu Runner." 
          echo "Runner OS: ${{ runner.os }}"